# Generated by Django 3.0.3 on 2020-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200529_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Moderate'), (3, 'Low')], default=3),
        ),
    ]
