# Generated by Django 3.0.3 on 2020-05-30 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200530_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
